# Default values for gloo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  type: NodePort
  replicaCount: 1
  port: 8080
  securePort: 8443
  adminPort: 19000
  image: "soloio/envoy"
  imageTag: "v0.1.5-81"
  imagePullPolicy: IfNotPresent

gloo:
  replicaCount: 1
  port: 8081
  image: "soloio/gloo"
  imageTag: "v0.1.5-81"
  imagePullPolicy: IfNotPresent

#  extra
gloo_function_discovery:
  image: soloio/gloo-function-discovery
  imageTag: v0.1.4
  imagePullPolicy: IfNotPresent
  enable: true

gloo_ingress_controller:
  image: soloio/gloo-ingress-controller
  imageTag: v0.1.1
  imagePullPolicy: IfNotPresent
  enable: true

gloo_k8s_service_discovery:
  image: soloio/gloo-k8s-service-discovery
  imageTag: v0.1.1
  imagePullPolicy: IfNotPresent
  enable: true

opentracing:
  imagePullPolicy: IfNotPresent
  enable: false
  jaeger: jaegertracing/all-in-one:latest
  jaeger_host: jaeger.server
  jaeger_port: 9123
  status: disable

metrics:
  imagePullPolicy: IfNotPresent
  enable: true
  service_monitor: false 
  prometheus_op: true 
  statsd_exporter: prom/statsd-exporter:latest
  statsd_host: statsd.server
  statsd_port: 9451
  status: all

prometheus:
  serviceMonitors:
  - name: "statsd-service-monitor"
    selector:
      matchLabels:
        app: statsd
    endpoints:
    - port: statsd
  
grafana:
  service:
    type: NodePort